### ISSUE TITLE
eligibility constraints

### ISSUE THREAD

**Issue by klambacher** [openreferral/specification#156] opened 2017-08-09 14:40 UTC
The eligibility table allows a string with includes a constraint with a set of enums. This does not fit any of our data for any client and the values are not even close to sufficiently inclusive; I would say it is impossible to come up with an exhaustive list that could be used as a limiter here, so I would strongly recommend not having one at all. 

In addition, we have a requirement to record minimum and maximum age data which is used for searching purposes. Is possible to recommend a structured format for an entry that describes an age range, so that it could be consistently parsed?

**Comment by timgdavies** [comment] 2017-08-09 17:03
The current enum list, taken from 1.0 is:

* "adult"
* "child"
* "teen"
* "family"
* "female"
* "male"
* "Transgender"
* "Transgender - M to F"
* "Transgender - F to M"

I would agree this is too limited, and getting to a full list too complex.

@greggish might be able to offer some context on the history of this list, and whether there is a case for trying to keep something standardised, or whether there should be a proposal to drop the codelist from a future version.

I'm going to open a separate issue on age eligibility...

**Comment by todrobbins** [comment] 2017-08-09 18:15
Is it conventional thinking to capitalize transgender? Or is that just a remnant of combining various enum lists?

**Comment by timgdavies** [comment] 2017-08-09 18:35
I believe this would be a remnant of earlier lists.

**Comment by greggish** [comment] 2017-08-10 17:36
I don't think this was intended to be a formal set. It might have just been a set of examples.  

Note that we can point to the [OpenEligibility](https://github.com/openreferral/openeligibility) 'Human Situations' taxonomy as a default reference set, although that too would have to evolve.

**Comment by robredpath** [comment] 2020-02-17 13:33
MINOR - remove the constraint

MAJOR - refactor to taxonomy

**Comment by mrshll1001** [comment] 2023-11-21 14:39
I am closing this because:

* 3.0 appears to have refactored this towards using taxonomies, while there remains explicit `eligibility_description`, `maximum_age`, and `minimum_age` fields which meet the modelling needs described. This addresses the original issue description.
* There is ongoing discussion and research into how best to model eligibility. This is out of scope for this issue by itself, however I've noted this link down to ensure that the issue is referenced as part of the ongoing discussion.

**Closed by mrshll1001** 2023-11-21 14:39 UTC
Labels: schema, MINOR upgrade, MAJOR upgrade
